-- CREATE A DATABASE
CREATE DATABASE XYZ;

-- USE DATABASE
USE XYZ;

-- CREATE A TABLE
CREATE TABLE EMPLOYEE_INFO(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
SALARY INT NOT NULL);

-- INSERT VALUES
INSERT INTO EMPLOYEE_INFO
(ID , NAME , SALARY)
VALUES
(1 , 'ADAM' , 2500) ,
(2 , 'BOB' , 30000) ,
(3 , 'CASEY' , 40000);

SELECT *FROM EMPLOYEE_INFO;